name: Push to Individual Repo on Main Branch Update

on:
  push:
    branches:
      - main

jobs:
  push-to-individual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the team repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Individual Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_REPO_TOKEN }}
        with:
          source-directory: "." # 현재 프로젝트 전체
          destination-github-username: "holdn2"
          destination-repository-name: "KU-ROOM-Web-Individual"
          target-branch: main
          user-email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit-message: "Auto commit from team repository [skip ci]"
          force: true
