name: Push to Individual Repo on Main Branch Update

on:
  push:
    branches:
      - main

jobs:
  push-to-individual:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the team repository with token
        env:
          PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          # 팀 레포를 Token으로 clone
          git clone https://x-access-token:${PERSONAL_REPO_TOKEN}@github.com/KU-rum/KU-ROOM-Web.git cloned-repo
          cd cloned-repo

          # Git 사용자 설정
          git config user.name "ljh130334"
          git config user.email "ljh130334@naver.com" # ← 여기는 본인 GitHub 이메일로 바꿔주세요

          # ✅ origin을 개인 레포로 변경
          git remote set-url origin https://x-access-token:${PERSONAL_REPO_TOKEN}@github.com/holdn2/KU-ROOM-Web-Individual.git

          # ✅ 강제 Push
          git push origin main --force
