name: Push to Individual Repo on Main Branch Update

on:
  push:
    branches:
      - main

jobs:
  push-to-individual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout team repository
        env:
          PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          # ✅ 팀 레포(KU-rum/KU-ROOM-Web)만 clone
          git clone https://x-access-token:${PERSONAL_REPO_TOKEN}@github.com/KU-rum/KU-ROOM-Web.git cloned-repo
          cd cloned-repo

          # 사용자 설정
          git config user.name "ljh130334"
          git config user.email "ljh130334@naver.com"

          # ✅ origin을 개인 레포로 변경
          git remote set-url origin https://x-access-token:${PERSONAL_REPO_TOKEN}@github.com/holdn2/KU-ROOM-Web-Individual.git

          # ✅ 개인 레포로 push
          git push origin main --force
