name: Push to Individual Repo on Main Branch Update

on:
  push:
    branches:
      - main

jobs:
  push-to-individual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Configure Git
        run: |
          git config user.name "holdn2"
          git config user.email "yoocy01@gmail.com"

      - name: Push to Personal Repository
        env:
          PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PERSONAL_REPO_TOKEN}@github.com/holdn2/KU-ROOM-Web-Individual.git
          git push origin main
